---
name: Build and Push Python Image to Google Cloud Platform
on:
  push:
    branches: [ main ]

jobs:
  build-push-gcr:
    permissions:
      contents: 'read'
      id-token: 'write'

    name: Build and Push to GCP
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: my-image
      PROJECT_ID: rare-mechanic-358909
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name:  Run multiline script
      run: |
        echo what is this directory?
        ls -a
        echo what environment variables are available
        echo "GITHUB_SHA=$GITHUB_SHA"
    - name:  Set environment variable
      run: |
        echo git_sha=`echo $GIT_SHA | cut -c -8` >> $GITHUB_ENV
        echo "ENVIRONMENT=dev" >> $GITHUB_ENV

    - name:  Get environment value
      run: echo "ENVIRONMENT=$ENVIRONMENT"
      env:
        IMAGE_TAG: ${{ env.ENVIRONMENT }}

    - name:  Get Image tag
      run: |
        echo "echo IMAGE_TAG:$IMAGE_TAG"                    

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        workload_identity_provider: 'projects/325316670694/locations/global/workloadIdentityPools/github-actions/providers/github-actions'
        service_account: 'my-service-account@rare-mechanic-358909.iam.gserviceaccount.com'
        
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0'

    - name: Build Docker Image
      run: docker build -t $IMAGE_NAME:latest .

    - name: Configure Docker Client
      run: |-
        gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

    - name: Push Docker Image to Artifact Registry
      env:
        GIT_TAG: ${{ env.git_sha }}-${{ env.ENVIRONMENT }}
      run: |-
        docker tag $IMAGE_NAME:latest us-central1-docker.pkg.dev/$PROJECT_ID/artifacts/$IMAGE_NAME:latest
        docker tag $IMAGE_NAME:latest us-central1-docker.pkg.dev/$PROJECT_ID/artifacts/$IMAGE_NAME:$GIT_TAG
        docker push us-central1-docker.pkg.dev/$PROJECT_ID/artifacts/$IMAGE_NAME:latest
        docker push us-central1-docker.pkg.dev/$PROJECT_ID/artifacts/$IMAGE_NAME:$GIT_TAG            


